development:
  adapter: postgresql
  encoding: unicode
  database: time_to_answer_development
  pool: 5
  username: postgres
  password: '123456'

test:
  adapter: postgresql
  encoding: unicode
  database: time_to_answer_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: time_to_answer_production
  pool: 5
  username: sample_postgres
  password: